# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise32"
  config.vm.box_url = "http://files.vagrantup.com/precise32.box"

  config.vm.synced_folder "../", "/source"

  config.vm.provider :virtualbox do |vb|
    # Don't boot with headless mode
    vb.gui = true
    
    # Use VBoxManage to customize the VM. For example to change memory:
    vb.customize ["modifyvm", :id, "--memory", "512", "--name", "sensor"]
  end

  config.vm.provision "shell",
    inline: "/vagrant/build-sensor.sh"
  
end
